image:
  repository: prometheus-alert-readiness
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

configuration:
  prometheusEndpoint: 'http://localhost:9090'
  prometheusApiTimeout: 4
  prometheusAlertSeverities: 'critical,warning'
  kubeLivenessPath: '/live'
  kubeReadinessPath: '/ready'
  kubeReadinessTiming:
    failureThreshold: 1     # if ever an alert is firing, immediately go NotReady
    initialDelaySeconds: 0  # Kubernetes default
    periodSeconds: 5        # Faster than the Kubernetes default: the faster we probe, the quicker we stop the rolling update
    successThreshold: 24    # Ensures that we wait at least 5 * 24 = 2 minutes to resume rolling the cluster, in case alerts flap
    timeoutSeconds: 5       # In line with prometheusApiTimeout and periodSeconds
  kubePodPriorityClass: 'system-cluster-critical'
  kubeProbeListenPort: 8080
